services:
  app:
    build: .
    container_name: charity-app
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/charity-donation
      - NODE_ENV=production
      - FRONTEND_URL=https://apex.maqsatto.tech
    depends_on:
      - mongo
    networks:
      - charity-net

  mongo:
    image: mongo:7
    container_name: charity-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - charity-net

  nginx:
    image: nginx:alpine
    container_name: charity-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - charity-net

  certbot:
    image: certbot/certbot
    container_name: charity-certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mongo-data:

networks:
  charity-net:
    driver: bridge
